### ISSUE TITLE
Can anyone please tell me how the connection is established between 2 devices(Android) and how they are connected to each other after scanning QRCode 

### ISSUE THREAD

**Issue by shwetankbhardwaj** [couchbaselabs/photo-drop#13]
Hello , 
I am unable to identify how the devices are connected to each other after scanning the QRCode.
If you can please guide me how to connect devices before scanning QRCode or the application does it automatically.
@hideki

**Comment by tahmmee** [comment]
The device presenting the QRCode is running a lite serve on the receiving end.  It's using the QRCode as a way to broadcast it's receiving url to the senders.  A sending device can scan this code to get the receivers url and set up a push replication for sending media to the receiving device.

Here is where the code is scanned, translated to a url and replication is done on the client:
https://github.com/couchbaselabs/photo-drop/blob/master/ios/PhotoDrop/SendViewController.swift#L123

Meanwhile, the receiving device is just running a listener:
https://github.com/couchbaselabs/photo-drop/blob/master/ios/PhotoDrop/ReceiveViewController.swift#L104
